version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    #    image: mongo
    build: .
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: reactivedb
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network

  postgres-admin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 8085:80
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@teste.com
      PGADMIN_DEFAULT_PASSWORD: teste
    links:
      - postgres
    networks:
      - postgres-compose-network

  postgres:
    #    image: postgres
    build:
      context: .
      dockerfile: DockerfilePostgres
    container_name: postegresdb
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network

networks:
  mongo-compose-network:
  postgres-compose-network:
