spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: user123
      password: pass123
      database: reactivedb
      repositories:
        enabled: false
#  main:
#    allow-bean-definition-overriding: true
logging.level.io.r2dbc: TRACE
